name: CI hello
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  CI:
    name: Publish hello app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      -
        name: Call Dagger Function
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: publish
          module: github.com/shykes/daggerverse/hello@v0.1.2
          args: --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}